-- MySQL Script generated by MySQL Workbench
-- Wed Apr 16 11:54:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuarios` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombreTipo_usuario` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `userID` INT NULL,
  PRIMARY KEY (`id_tipo_usuario`),
  UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`id_tipo_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `id_tipo_usuario` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `userID` INT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_usuario_tipo_usuario1_idx` (`id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `mydb`.`tipo_usuarios` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_copy1` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bodegas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bodegas` (
  `id_bodega` INT NOT NULL AUTO_INCREMENT,
  `cantidad_material` INT NOT NULL,
  `descripcion_material` VARCHAR(200) CHARACTER SET 'ascii' NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `userID` INT NULL,
  PRIMARY KEY (`id_bodega`),
  UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`id_bodega` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`V_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`V_usuario` (
  `id_V_usuario` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(200) BINARY NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_V_usuario`, `id_tipo_usuario`),
  UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`id_V_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`logistica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`logistica` (
  `id_logistica` INT NOT NULL AUTO_INCREMENT,
  `cantidad_P` INT NOT NULL,
  `reporte_P` VARCHAR(200) NOT NULL,
  `nombre_P` VARCHAR(50) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `id_v_usuario` INT NOT NULL,
  `id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_logistica`, `id_v_usuario`, `id_tipo_usuario`),
  UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`id_logistica` ASC) VISIBLE,
  INDEX `fk_logistica_V_usuario1_idx` (`id_v_usuario` ASC, `id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_logistica_V_usuario1`
    FOREIGN KEY (`id_v_usuario` , `id_tipo_usuario`)
    REFERENCES `mydb`.`V_usuario` (`id_V_usuario` , `id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`S_obrero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`S_obrero` (
  `id_S_obrero` INT NOT NULL AUTO_INCREMENT,
  `nombre_materiales` VARCHAR(50) NOT NULL,
  `cantidad_materiales` INT NOT NULL,
  `consulta_dispo` VARCHAR(200) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `id_v_usuario` INT NOT NULL,
  `id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_S_obrero`, `id_v_usuario`, `id_tipo_usuario`),
  UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`id_S_obrero` ASC) VISIBLE,
  INDEX `fk_s_obrero_V_usuario1_idx` (`id_v_usuario` ASC, `id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_s_obrero_V_usuario1`
    FOREIGN KEY (`id_v_usuario` , `id_tipo_usuario`)
    REFERENCES `mydb`.`V_usuario` (`id_V_usuario` , `id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personas` (
  `rut` INT NOT NULL AUTO_INCREMENT,
  `nombre_p` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(40) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(40) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_tipo_usuario` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `userID` INT NULL,
  PRIMARY KEY (`rut`),
  UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`rut` ASC) VISIBLE,
  INDEX `fk_personas_usuario1_idx` (`id_usuario` ASC, `id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_personas_usuario1`
    FOREIGN KEY (`id_usuario` , `id_tipo_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario` , `id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materiales` (
  `id_materiales` INT NOT NULL AUTO_INCREMENT,
  `id_bodega` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `userID` INT NULL,
  PRIMARY KEY (`id_materiales`),
  UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`id_materiales` ASC) VISIBLE,
  INDEX `fk_materiales_bodega1_idx` (`id_bodega` ASC) VISIBLE,
  CONSTRAINT `fk_materiales_bodega1`
    FOREIGN KEY (`id_bodega`)
    REFERENCES `mydb`.`bodegas` (`id_bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventarios` (
  `id_inventario` INT NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NOT NULL,
  `id_materiales` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `userID` INT NULL,
  PRIMARY KEY (`id_inventario`),
  UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`id_inventario` ASC) VISIBLE,
  INDEX `fk_inventario_materiales1_idx` (`id_materiales` ASC) VISIBLE,
  CONSTRAINT `fk_inventario_materiales1`
    FOREIGN KEY (`id_materiales`)
    REFERENCES `mydb`.`materiales` (`id_materiales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_movimientos` (
  `id_estado_movimiento` INT NOT NULL AUTO_INCREMENT,
  `estado_movimiento` VARCHAR(50) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `userID` INT NULL,
  PRIMARY KEY (`id_estado_movimiento`),
  UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`id_estado_movimiento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_movimientos` (
  `id_tipo_movimiento` INT NOT NULL AUTO_INCREMENT,
  `ingreso` VARCHAR(45) NOT NULL,
  `salida` VARCHAR(45) NOT NULL,
  `ajuste` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `userID` INT NULL,
  PRIMARY KEY (`id_tipo_movimiento`),
  UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`id_tipo_movimiento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movimientos` (
  `id_movimiento` INT NOT NULL AUTO_INCREMENT,
  `id_estado_movimiento` INT NOT NULL,
  `id_tipo_movimiento` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_materiales` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `userID` INT NULL,
  PRIMARY KEY (`id_movimiento`),
  UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`id_movimiento` ASC) VISIBLE,
  INDEX `fk_movimiento_estado_movimiento1_idx` (`id_estado_movimiento` ASC) VISIBLE,
  INDEX `fk_movimiento_tipo_movimiento1_idx` (`id_tipo_movimiento` ASC) VISIBLE,
  INDEX `fk_movimiento_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_movimiento_materiales1_idx` (`id_materiales` ASC) VISIBLE,
  CONSTRAINT `fk_movimiento_estado_movimiento1`
    FOREIGN KEY (`id_estado_movimiento`)
    REFERENCES `mydb`.`estado_movimientos` (`id_estado_movimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_tipo_movimiento1`
    FOREIGN KEY (`id_tipo_movimiento`)
    REFERENCES `mydb`.`tipo_movimientos` (`id_tipo_movimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_materiales1`
    FOREIGN KEY (`id_materiales`)
    REFERENCES `mydb`.`materiales` (`id_materiales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;